server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ferlisi05/spring-cloud-config-store
          search-paths:
           - '*service'

service:
    greeting: Hello from DEFAULT !!!!  
    
    
    