service: 
    greeting: Hello from DEFAULT 

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SAMPLE?createDatabaseIfNotExist=true
    username: root
    password: ferlis05
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
